// transitions.ts — Transition directory. Each drops into a clip's ACTION (the
// transition into/out of a clip lives in the Action, not a separate field).
// "Take transitions" mirror the ones already selectable on the export panels;
// "Single-take world-swaps" are continuous in-camera transitions.
import type { LibraryCategory } from "../components/PromptLibrary";

export const TRANSITION_CATEGORIES: LibraryCategory[] = [
  {
    title: "Take transitions (built-in)",
    blurb: "The cuts written between takes — also selectable on the Showrunner / Seedance panels. Paste one into an Action to force it in a single clip.",
    entries: [
      { name: "Hard Cut", prompt: "Hard cut, no dissolve — cut directly on action into the next shot's opening frame." },
      { name: "Cut to Black", prompt: "Cut to black for a beat (about half a second), then cut in on the next shot's opening frame." },
      { name: "Dissolve", prompt: "Cross-dissolve from the last frame of this shot into the next shot's opening frame." },
      { name: "Whip Pan", prompt: "Whip the camera hard to one side, the frame smearing into motion blur, and continue that same blur speed into the next shot so the two read as one movement — landing on the next cast and set." },
      { name: "Match Cut", prompt: "Match cut on a shared shape, motion or position into the next shot — the same framing carried across the cut, new cast and set." },
      { name: "Push-Through Object", prompt: "Push forward through a foreground object filling the frame (a hand, a doorway, a flame), and continue that same push out the other side into the next shot's cast and set." },
    ],
  },
  {
    title: "Single-take world-swaps",
    blurb: "Continuous in-camera transitions — one unbroken take where a wipe, flame, whip, crest or tunnel carries you from one world to another with the subject unchanged.",
    entries: [
      { name: "Palm wipe world-swap", prompt: "A single unbroken take with no cut at any point and no dissolve. A vertical locked off close on a face in a dim room. A hand sweeps across the lens very close, the palm filling the entire frame for about half a second, and when it clears the same person is in a completely different room in different clothing, seated the same way in the same position in frame, so one setting at the start is another by the end with the person unchanged. The camera does not move. Warm dim light, then cool daylight. 50mm, shallow depth of field. About 6 seconds, no loop. <a soft rush past the lens, the room tone changing>. No music." },
      { name: "Through the flame", prompt: "Two shots joined through a flame. First half, a vertical push toward a single candle on a table in a dark room until the flame fills the centre of frame and the surround goes black. The second half continues the same push out of an identical flame in a different room, pulling back to reveal a bright kitchen in daylight, so a dark interior at the start is a lit kitchen by the end and the flame is the passage between them. Deep black and warm flame, then flat daylight. 85mm, very shallow depth of field, film grain. About 6 seconds, no loop. <a room tone with a wick guttering, then daytime kitchen sound> (a low tone lifting as it emerges)." },
      { name: "The flame stays, the room goes", prompt: "A single unbroken take with no cut at any point and no dissolve. A locked off close on a single candle flame held dead centre and burning steadily for the whole take. The flame never gutters, moves or changes size. Behind it the room changes continuously from a bare stone cell to a richly furnished drawing room, the walls, the furniture and the depth all altering around the unchanged flame, so a cell at the start is a drawing room by the end. Deep dark either side with the flame as the only constant light. 85mm, very shallow depth of field. About 7 seconds, no loop. <silence, then a distant clock and voices>. No music. (Keep the flame fixed and steady — any flicker that matches the room change gives the join away.)" },
      { name: "She keeps walking, the street does not", prompt: "A single unbroken take with no cut at any point and no dissolve. A lateral tracking shot travelling at exactly walking pace beside a woman crossing frame left to right, holding her at a fixed size in the centre of frame. She never leaves frame and her stride never changes. Behind her the street changes continuously as she walks, the shopfronts, the parked cars and the light shifting from a modern high street to the same street fifty years earlier without anything cutting, so a contemporary street at the start is a historical one by the end and she has walked the whole way. Flat daylight throughout. Anamorphic, 35mm grain. About 10 seconds, no loop. <steady footsteps, the traffic behind her thinning to hooves>. No music." },
      { name: "The rain sheet crosses", prompt: "A single unbroken take with no cut at any point and no dissolve. A vertical locked off on a coastal path in light drizzle. A dense squall of rain sweeps across the frame from the right, thick enough to obscure everything for about three quarters of a second, and as it passes on the same path is dry cracked earth under hard sun with no rain at all, so a wet coastal path at the start is arid ground by the end. The camera does not move and the path stays in the same position. Grey wet light, then hot dry light. 35mm, film grain. About 6 seconds, no loop. <a squall crossing hard, then still dry air>. No music." },
      { name: "Whip left, arrive elsewhere", prompt: "Two shots joined by a whip. First half, a static shot of a man at a workbench, then the camera whips hard to the left, the frame smearing into pure motion blur. The second half continues that same blur at the same speed and settles on a completely different place, a windswept beach, so a workshop at the start is a coastline by the end and the blur is shared between them. Warm interior, then flat grey daylight. 35mm, handheld, film grain. About 6 seconds, no loop. <a rush of air with the room tone swapping inside it> (a percussive hit as it settles)." },
      { name: "Over the ridge, another age", prompt: "Two states joined over a crest. A continuous rise up the near face of a grassy ridge with nothing visible beyond it, the camera climbing at a steady rate until the far side comes into view, and what is revealed is the same valley in a different age, forested and unbuilt where a town stood in the establishing glimpse, so a modern approach at the start is an untouched valley by the end and the ridge line hides the change. Flat overcast light throughout, unchanged. Anamorphic, 35mm grain, one continuous take. About 10 seconds, no loop. <wind, with distant traffic fading out as the far side appears> (a low drone thinning across the crest)." },
      { name: "Out of the tunnel, elsewhere", prompt: "Two shots joined in darkness. First half, a forward move through a road tunnel at speed with lights streaking past, entering a long unlit section where the frame goes almost black. The second half exits at the same speed from the same tunnel mouth into a completely different landscape, an alpine pass instead of the city that went in, so an urban approach at the start is a mountain road by the end. Streaked sodium, then hard clear daylight. Anamorphic, 35mm grain. About 8 seconds, no loop. <tunnel roar dropping to open wind> (a chord resolving on the exit)." },
    ],
  },
];
